### ISSUE TITLE
calibre does not exit with an error code when appropriate

### ISSUE THREAD

**Issue by markdorison** [calibreapp/cli#10]
## CLI Installation method

* [x] NPM
* [ ] Binary

## Operating system

* [x] Mac
* [ ] Windows
* [ ] Linux

## What you expected to happen

When an error occurs, calibre should exit with a non-zero error-code.

## What happened

When an error is encountered, calibre exits with a `0` code.

## Steps to Reproduce (for bugs)

1. `npm install --save calibre`
2. `npx calibre site create-snapshot --site=INCORRECT_SITE_NAME --json`
3. `echo $?`

**Comment by benschwarz** [comment]
We just released 1.2.0 which has far better error handling (and will result in the correct exit code). Thanks for logging this @markdorison
