### ISSUE TITLE
'calibre site pages' should return slug of the page

### ISSUE THREAD

**Issue by bsuchodolski-ng** [calibreapp/cli#11]
When I list my sites via CLI, apart from the name that is displayed in the calibre ui I also get site's slug:

```
calibre site list --json

[
  {
    "name": "FirstSite Name",
    "slug": "firstsite-name",
    "createdAt": "2015-05-19T07:23:39Z"
  },
  {
    "name": "SecondSite (Something)",
    "slug": "secondsite-something",
    "createdAt": "2015-10-05T09:42:53Z"
  }
]
```

But when I'm fetching list of pages for the site I'm getting only original name of the page and its uuid:

```
calibre site pages --site=firstsite-name --json

[
  {
    "uuid": "uuid1",
    "name": "Name Of The Page With Spaces",
    "url": "https://legiturl.com/",
    "canonical": true
  },
  {
    "uuid": "uuid2",
    "name": "Weird (N)a me",
    "url": "https://legiturl.com/2",
    "canonical": false
  }
]
```

If I want to get pulse metrics for particular page I have to guess its slug, because I can't use uuid there.

Shouldn't `calibre site pages` return also page's slug? 🤔

**Comment by benschwarz** [comment]
Hey @bsuchodolski-ng, 

I responded to you in support chat, but I thought it'd be good to have a public follow up too. 
I've merged #13 with fixes to the issue that you've raised. 

CLI should always encourage people to use UUID's for resources (except for Sites, which will use slugs). The changes reflect that.
