### ISSUE TITLE
Show Speed Index in metrics list

### ISSUE THREAD

**Issue by darylljann** [calibreapp/cli#17]
## CLI Installation method

* [x] NPM / NPX
* [ ] Binary

## Operating system

* [x] Mac
* [ ] Windows
* [ ] Linux

## What you expected to happen
Expecting Speed Index to be included in the metrics list

## What happened

N/A

## Steps to Reproduce

```
calibre site get-pulse-metrics --site=site-name --page=page-slug --metrics
```

**Comment by benschwarz** [comment]
Hey @darylljann, thanks for logging this. 

We've added `speed_index` as an API fetchable metric, the deploy for that will hit our servers soon, there won't be any need to upgrade your CLI version. 

As an aside, we don't really recommend that people use speed index as it can be easily aligned with other, easier to understand paint metrics (eg, non technical people get it!).

**Comment by darylljann** [comment]
Great news, thanks for that info! Looking forward to check it out it via CLI 🚀 

And agreed, we're using the paint metrics to explain to non-devs. But just a quick background - we've used speed index combined with a dollar per page value (Top URLs) to get the impact per page value when optimising target URLs.

**Comment by benschwarz** [comment]
@darylljann Sounds fascinating, I'd love to see this sometime. (Or do a case study with you?)

**Comment by darylljann** [comment]
Of course, I think that would be really cool. I'll keep you posted once we have the report ready.
