### ISSUE TITLE
command not found?

### ISSUE THREAD

**Issue by sharedphysics** [calibreapp/cli#2]
I keep getting `calibre: command not found` when trying to run in terminal (mac). Installation and setup with API seemed to go through successfully and pretty straightforward. Am I missing something basic? :)

**Comment by benschwarz** [comment]
@sharedphysics which installation method did you use?

**Comment by sharedphysics** [comment]
@benschwarz - Install via NPM. Tried via local directory too and ran into some different trouble, file is locked/didn't have permissions to make it executable.

**Comment by benschwarz** [comment]
@sharedphysics, I should've thought to ask earlier, can you tell me: 

* Operating system
* Node version
* Paste any errors you've seen for the installation phase

---

It so far sounds as though your node permissions are preventing the CLI from being installed globally. I found [this article](https://docs.npmjs.com/getting-started/fixing-npm-permissions) that might help that setup issue. 

As for the local install, could you share the error message that you saw?

In the meantime, if you'd prefer to try some alternative options: 

* Always run Calibre's CLI via ["NPX"](http://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner): `npx calibre --help`
* [Download & Install](https://calibreapp.com/docs/api/binaries) a standalone binary of CLI (No node installation required)

**Comment by sharedphysics** [comment]
@benschwarz -> Thanks, running the `NPX` command  seemed to work. I then ran into permissions issues, and `sudo chmod +x /usr/local/bin/calibre` fixed the permissions issue. Ran my first CLI test. Pretty cool!
