### ISSUE TITLE
get-all-pulse-metrics.js -> Variables

### ISSUE THREAD

**Issue by sharedphysics** [calibreapp/cli#29]
I've successfully run + output the 7-days and (30 days) script to JSON. Fiddling around with it, it would be good to be able to adjust variables:
$sites 
$pages
$duration
$metrics retrieved

For example:

```
    // Iterate through each page, returning a promise for the metrics being fetched
    return Promise.all(pages.map(async page => {
      const pulse = await SnapshotMetrics.pulse({
        site: site.slug,
        page: page.uuid,
        durationInDays: 30,
        metrics: ['consistently-interactive']
      })

      // Update the allPulseMetrics hash with metrics for this page
      allPulseMetrics[site.slug][page.uuid] = {
        page: page,
        pulse: pulse
      }
```

When I modified `metrics: ['consistently-interactive']` to `metrics: ['consistently-interactive','meaningful-paint']`, I got back `(node:84764) UnhandledPromiseRejectionWarning: [object Array]` and when I tried other variations, I got back other similar errors. I also did not know which variables to put into metrics, because they are not named 1:1 with the desktop UI labels.

**Comment by benschwarz** [comment]
We've since released some changes to error handling that will return far more meaningful errors that will tell you what the options are. 

For first meaningful paint, the enum should be `['consistently-interactive', 'first-meaningful-paint']`.
