### ISSUE TITLE
Latest release of calibre broken in node 8 (v8.15.0), works in node 10

### ISSUE THREAD

**Issue by sync** [calibreapp/cli#41]
## CLI Installation method

* [x] NPM / NPX
* [ ] Binary

## Operating system

* [x] Mac
* [ ] Windows
* [x] Linux

## What you expected to happen

npx calibre site create-snapshot --site abc 

## What happened

it crashes

<details>
  <summary>Error: </summary>
  
npx: installed 205 in 11.696s
/Users/anthonymittaz/.npm/_npx/59370/lib/node_modules/calibre/src/cli/site/download-snapshot-artifacts.js:53
    for await (const page of response.pages) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at Object.require (internal/module.js:11:18)
    at /Users/anthonymittaz/.npm/_npx/59370/lib/node_modules/calibre/node_modules/require-directory/index.js:76:17
error Command failed with exit code 1.
</details>

## Steps to Reproduce (for bugs)

1. Use node 8, and latest calibre version: 1.2.0
2. npx calibre site create-snapshot --site abc 
3. crash boom

**Comment by benschwarz** [comment]
Thanks for logging this @sync. 

We used `for-await-of` for `download-snapshot-artifacts` which might've been a little heavy handed in terms of upgrade path. (Perhaps we could've called this a 2.0.0 release to signify a breaking change).

We'll figure out the next move and keep this issue updated

**Comment by sync** [comment]
thanks

**Comment by micdijkstra** [comment]
@sync We've just released 1.2.1 which should work on node 8.15.0 👌
