### ISSUE TITLE
Error: [object Object] returned from CLI in terminal and node script

### ISSUE THREAD

**Issue by allentingley** [calibreapp/cli#51]
## CLI Installation method

* [X] NPM / NPX
* [ ] Binary

## Output of `calibre --version`
1.2.4

## Operating system

* [X] Mac
* [ ] Windows
* [ ] Linux

## What you expected to happen

From both the terminal interface (calibre test create [url] --[location]) and from a node script (using the example provided) I expect to run a test and after some time results returned or any errors handled gracefully.

## What happened

<details>
  <summary>Error from Node Script: </summary>
(node:2085) UnhandledPromiseRejectionWarning: Error: [object Object]
    at Object.waitForTest (/Users/allen/traffic/node_modules/calibre/src/api/test.js:107:69)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:2085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Error from terminal CLI:

(in Red text): Error: [object Object]

</details>

## Steps to Reproduce (for bugs)

1. From the CLI Terminal, run tests on a sample site. 

After 3-4 tests the test will run for an extended period of time and this unhandled exception error will return: UnhandledPromiseRejectionWarning: Error: [object Object]

The number of tests before this error is returned has not been consistent. I was able to duplicate in both the example node script provided with the CLI and in the terminal using the CLI commands.

I've been unable to get any more information about the error other than the [object Object] portion.

**Comment by benschwarz** [comment]
Thanks for logging this @allentingley. 

We're going to issue a fix that'll likely go out with our 2.0.0 release.
