### ISSUE TITLE
Changing Setting for Test Profiles

### ISSUE THREAD

**Issue by bassettsj** [calibreapp/cli#6]
There are times that we will need to update our test profiles for cookies to provide required authentication information for example. Would it be possible to add this to the CLI?

Thanks :-)

**Comment by benschwarz** [comment]
Thanks for logging the issue @bassettsj, we'll track the progress here and will also follow up with you via support.

**Comment by benschwarz** [comment]
This was released in 1.0.8 :thumbsup:
