### ISSUE TITLE
Field 'createSnapshot' doesn't accept argument 'ref'

### ISSUE THREAD

**Issue by markdorison** [calibreapp/cli#9]
## CLI Installation method

* [x] NPM
* [ ] Binary

## Operating system

* [x] Mac
* [ ] Windows
* [x] Linux

## What you expected to happen

I expected `npx calibre site create-snapshot --site=SITENAME` to create a snapshot without an error.

## What happened

When attempting to create a snapshot, I received an error: `Field 'createSnapshot' doesn't accept argument 'ref'`

I was attempting to pass in a reference id with `--ref` but this error is occurring whether or not I specify a ref.

<details>
  <summary>Error: </summary>
  [ { message: 'Field \'createSnapshot\' doesn\'t accept argument \'ref\'',
    locations: [ [Object] ],
    fields: [ 'mutation CreateSnapshot', 'createSnapshot', 'ref' ] },
  { message: 'Variable $ref is declared by CreateSnapshot but not used',
    locations: [ [Object] ],
    fields: [ 'mutation CreateSnapshot' ] } ]
</details>

## Steps to Reproduce (for bugs)

1. `npm install --save calibre`
2. `npx calibre site create-snapshot --site=SITENAME`

**Comment by benschwarz** [comment]
@markdorison, thanks so much for the report. 

I've been making changes behind the scenes and it looks as though I let one through that shouldn't have gone through. 

We're going to make a fix immediately and roll it out in the next hour or so. Will keep you updated…

**Comment by markdorison** [comment]
@benschwarz I am now getting a 500 error. Detailed error output:

```
Connecting to Calibre(node:90733) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at Object.main [as handler] (/Users/mdorison/Sites/chromatichq.com/tests/calibre/node_modules/calibre/src/cli/site/create-snapshot.js:22:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:90733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:90733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇
```

**Comment by benschwarz** [comment]
@markdorison I believe the issue is solved, would you mind giving it one last verification?

**Comment by markdorison** [comment]
@benschwarz It looks like it is now resolved. Thanks for the assist.
